// Volecco landing copy — static JA/EN strings for the LP prototype.
(function () {
  const ja = {
    meta: {
      lang: "ja",
      title: "Volecco — 次にやるべきことを見つけよう",
      description: "人生の節目のためのチェックリスト・ナビゲーター。海外旅行、引越し、出産準備——見つけて、コピーして、ひとつずつ。",
    },
    nav: {
      links: [
        { id: "how", label: "仕組み" },
        { id: "demo", label: "デモ" },
        { id: "categories", label: "カテゴリ" },
        { id: "trust", label: "信頼性" },
      ],
      demo: "デモを見る",
      cta: "チェックリストを探す",
      menu: "メニュー",
      switchLanguage: "英語に切り替え",
      nextLanguage: "EN",
      switchToDark: "ダークテーマに切り替え",
      switchToLight: "ライトテーマに切り替え",
    },
    hero: {
      badge: "人生の節目のための、チェックリスト・ナビゲーター",
      titleLead: "次にやるべきことを",
      titleAccent: "見つけよう。",
      sub: ["海外旅行、引越し、出産準備。", "大事な場面ほど、", "「何か忘れてるかも」が消えない。", "Voleccoは、", "整えられたチェックリストを見つけて、", "コピーして、", "ひとつずつ進めるための場所です。"],
      cta: "チェックリストを探す",
      demo: "デモを試す",
      proof: [
        { icon: "doc", text: "出典・最終確認日つき" },
        { icon: "download", text: "直近の1リストをオフライン実行" },
        { icon: "shield", text: "実態のない評価なし" },
      ],
    },
    sections: {
      problem: {
        eyebrow: "THE PROBLEM",
        title: ["「何か忘れてる気がする」が、", "消えない。"],
        lead: ["新しい状況に放り込まれた瞬間から、", "急ごしらえの調べものが始まります。", "ブログ、動画、掲示板、", "家族のグループチャット。", "読むほどに情報は増えて、", "全体像はかえって遠ざかる。", "締切だけが近づいてくる。"],
        pivot: ["足りないのは情報じゃない。", "「これで全部」と言える一枚です。"],
        sources: [
          { id: "s1", label: "ブログ記事", icon: "doc", hue: 25, cls: "s1" },
          { id: "s2", label: "解説動画", icon: "play", hue: 350, cls: "s2" },
          { id: "s3", label: "掲示板スレッド", icon: "chat", hue: 280, cls: "s3" },
          { id: "s4", label: "SNSの投稿", icon: "globe", hue: 205, cls: "s4" },
          { id: "s5", label: "PDFガイド", icon: "note", hue: 150, cls: "s5" },
          { id: "s6", label: "グループチャット", icon: "users", hue: 60, cls: "s6" },
        ],
        chaosTitle: "どこから手をつける？",
        chaosQuestion: "3週間後、海外旅行",
      },
      solution: {
        eyebrow: "THE SOLUTION",
        title: ["散らばった知恵を、", "一枚のチェックリストに。"],
        lead: ["Voleccoは、", "経験から得た知恵や公的な情報を整理して", "「上から順に進められる」", "一枚にまとめた、", "チェックリストのライブラリ。", "見つけたら、", "コピーして自分のものに。", "あとは、ひとつずつ。"],
        tidyTitle: "海外旅行 — 出発前リスト",
        tidySections: [
          { title: "3週間前", items: ["パスポートの有効期限を確認", "ビザ・eTAの要否を確認", "海外旅行保険を契約"] },
          { title: "出発前夜", items: ["スーツケースの重量を確認", "自宅の戸締まりを確認"] },
        ],
        lastChecked: "最終確認 2026-05",
      },
      how: {
        eyebrow: "HOW IT WORKS",
        title: ["見つけてから、", "やり終えるまで。"],
        lead: ["面倒な設定も、", "空っぽのページもありません。", "「どこから？」が「次はこれ」に変わるまで、", "5つのステップ。"],
        steps: [
          { n: 1, icon: "search", en: "DISCOVER", title: "さがす", txt: "状況やキーワードから、いまの自分に合うチェックリストを見つける。" },
          { n: 2, icon: "note", en: "PREVIEW", title: "たしかめる", txt: "コピーする前に、中身をすべてプレビュー。納得してから選べる。" },
          { n: 3, icon: "copy", en: "COPY", title: "じぶんのものに", txt: "ワンタップでマイライブラリへ。ここからは独立した自分のデータ。" },
          { n: 4, icon: "edit", en: "PERSONALIZE", title: "ととのえる", txt: "チェック項目を足す、消す、並べ替える。自分の状況に合わせて作り変える。" },
          { n: 5, icon: "check", en: "EXECUTE", title: "すすめる", txt: "Next Actionが次の一手を示す。進み具合はボードが見せてくれる。" },
        ],
      },
      demo: {
        eyebrow: "THE EXPERIENCE",
        title: ["次の一手だけ、", "くっきり見える。"],
        lead: ["コピーしたリストはExecute画面へ。", "いま見るべきは", "Next Actionひとつだけ。", "進み具合は、", "駅の路線図のような", "JourneyTrackが教えてくれます。", "下のデモは実際にさわれます。"],
        points: [
          { icon: "flag", title: "Next Action", txt: "上から順に、最初の未完了がいつも一枚だけ大きく出る。迷う余地をなくす。" },
          { icon: "plane", title: "JourneyTrack", txt: "セクションを駅に見立てた進捗の路線図。いまどの駅で、終点まであとどれくらいかが見える。" },
          { icon: "spark2", title: "Focus Mode", txt: "ナビゲーションを隠して、目の前のリストだけに集中できる静かな画面。" },
          { icon: "download", title: "オフライン実行", txt: "直近で開いた1つの個人用リストを端末に保存。機内でも圏外でも実行できて、復帰したら自動で同期。" },
        ],
      },
      categories: {
        eyebrow: "CATEGORIES",
        title: ["まずは、", "3つの節目から。"],
        lead: ["いきなり何百種類ではなく、", "チェックリストの質が", "いちばん効く場面から。", "どのリストも管理者が精査し、", "判断に関わるリストには", "出典と最終確認日を添えて公開します。"],
        note: "カテゴリは、ここから少しずつ増えていきます。",
        preview: "プレビューを見る",
        lastChecked: "最終確認 2026-05",
        cards: [
          { coverLabel: "サンプル: 出発前チェックリスト", hue: 250, catIcon: "plane", cat: "海外旅行", title: "海外旅行の準備", blurb: "パスポートから機内持ち込みまで。出発までの数週間を、時系列で迷わず進める。", meta: "24項目 · 4セクション" },
          { coverLabel: "サンプル: 引越しチェックリスト", hue: 195, catIcon: "home", cat: "引越し・一人暮らし", title: "引越しと新生活の立ち上げ", blurb: "退去の連絡からライフラインの開通、最初の夜の段ボールまで。順番どおりにやれば着地できる。", meta: "28項目 · 5セクション" },
          { coverLabel: "サンプル: 出産準備チェックリスト", hue: 25, catIcon: "sparkles", cat: "出産準備", title: "出産前後の準備", blurb: "入院バッグから産後の手続きまで。からだ最優先で進められるよう、急がない順番で。", meta: "26項目 · 5セクション" },
        ],
      },
      trust: {
        eyebrow: "TRUST",
        title: ["「信じて任せられる」を、", "設計する。"],
        lead: ["チェックリストは、", "人の判断に影響するものです。", "だからVoleccoは、", "にぎやかな数字より、", "確かめられる根拠を優先します。"],
        note: ["各リストは準備の補助です。", "出典と最終確認日を明記し、", "判断に関わるリストでは公的機関の最新情報の確認も促します。"],
        cards: [
          { kicker: "SOURCED", title: "出典と最終確認日", txt: "防災・医療・行政手続きなど判断に関わるリストには、参照元と最終確認日を明記。「最新の公的情報を確認する」こと自体も項目に含めます。" },
          { kicker: "NO FAKE STARS", title: "実態のない評価を載せない", txt: "実態のない星やレビューは載せません。Curated / Reviewed / Copied など、事実にもとづく表示だけを使います。" },
          { kicker: "OFFLINE FIRST", title: "電波がなくても動く", txt: "直近で開いた1つの個人用リストを端末に保存。機内でも、ネットの通っていない新居でも実行できて、復帰したら自動で同期します。" },
          { kicker: "YOUR COPY", title: "コピーしたリストは、あなたのもの", txt: "コピーした瞬間から独立した個人データ。元のリストが更新されても、あなたの一枚が勝手に書き換わることはありません。" },
        ],
      },
      philosophy: {
        eyebrow: "PHILOSOPHY",
        statementLead: "経験を、",
        statementAccent: "行動",
        statementTail: "に。",
        sub: ["チェックリストは、", "ただのToDoではなく", "「再利用できる知識」のかたち。", "誰かが学んだ順番が、", "次の誰かの不安を消していく。", "Voleccoは、", "そのための静かな図書館です。"],
        pills: ["タスク管理ツールではない", "Wikiではない", "SNSではない", "再利用できる知識のライブラリ"],
      },
      finalCta: {
        eyebrow: "READY WHEN YOU ARE",
        title: ["迷う時間を、", "進む時間に。"],
        sub: ["状況を選んで、", "チェックリストをコピーして、", "最初のチェック項目を完了に。", "「次にやるべきこと」は、", "もう探さなくていい。"],
        cta: "チェックリストを探す",
        how: "仕組みを見る",
      },
      footer: {
        tag1: ["人生の節目のための、", "チェックリスト・ナビゲーター。", "「次にやるべきこと」が", "いつも見えるように。"],
        tag2: ["現在は管理者キュレーション型βとして準備中。", "まずはWebアプリとして、", "スマホのブラウザでも使える体験を優先します。"],
        product: "プロダクト",
        links: [
          ["how", "仕組み"],
          ["demo", "デモ"],
          ["categories", "カテゴリ"],
          ["trust", "信頼性"],
        ],
        copy: "© 2026 Volecco — Curated checklists（β）",
      },
    },
    mockups: {
      situations: [
        { flap: "OVERSEAS TRIP", status: "NOW BOARDING", tone: "next", step: "パスポートの有効期限を確認", label: "海外旅行" },
        { flap: "MOVING HOUSE", status: "ON TIME", tone: "live", step: "退去の連絡を入れる", label: "引越し" },
        { flap: "NEW BABY", status: "STAND BY", tone: "todo", step: "チャイルドシートを設置", label: "出産準備" },
        { flap: "NEW APARTMENT", status: "ON TIME", tone: "live", step: "電気・ガス・水道を開通", label: "一人暮らし" },
        { flap: "BIRTH PREP", status: "NOW BOARDING", tone: "next", step: "入院バッグを用意", label: "出産準備" },
        { flap: "VISA & DOCS", status: "STAND BY", tone: "todo", step: "ビザの要否を確認", label: "ビザ・書類" },
      ],
      bigBoard: { live: "VOLECCO · DEPARTURES", cols: ["SITUATION", "STATUS", "NEXT STEP — 次にやること"], aria: "次にやること" },
      execute: {
        tryMe: "TRY ME — さわれます",
        title: "海外旅行 — 出発前チェックリスト",
        category: "海外旅行",
        doneUnit: "完了",
        pctDone: "完了",
        nextAction: "NEXT ACTION — 次にやること",
        markDone: "この項目を完了にする",
        celebrate: "全部終わりました。おつかれさま。",
        reset: "リセット",
        catName: "Travel",
        sections: [
          { title: "3週間前", items: [{ text: "パスポートの有効期限を確認", done: true }, { text: "ビザ・eTAの要否を確認", done: true }, { text: "海外旅行保険を契約", done: true }] },
          { title: "出発1週間前", items: [{ text: "オフライン地図をダウンロード", done: true }, { text: "パスポートとカードのコピーを取る", done: false }, { text: "不在中の連絡先を家族に共有", done: false }] },
          { title: "機内持ち込み", items: [{ text: "充電器とモバイルバッテリー", done: false }, { text: "常備薬を元の容器のまま", done: false }] },
        ],
      },
      miniBoard: { live: "NOW BOARDING", cols: "状況 · 次の一歩", nextStep: "NEXT STEP" },
    },
    common: { curated: "CURATED" },
  };

  const en = {
    meta: {
      lang: "en",
      title: "Volecco — Find Your Next Step",
      description: "A checklist navigator for life's turning points. Overseas travel, moving, birth preparation — find a checklist, copy it, and move one step at a time.",
    },
    nav: {
      links: [
        { id: "how", label: "How it works" },
        { id: "demo", label: "Demo" },
        { id: "categories", label: "Categories" },
        { id: "trust", label: "Trust" },
      ],
      demo: "View demo",
      cta: "Find a checklist",
      menu: "Menu",
      switchLanguage: "Switch to Japanese",
      nextLanguage: "JA",
      switchToDark: "Switch to dark theme",
      switchToLight: "Switch to light theme",
    },
    hero: {
      badge: "A checklist navigator for life's turning points",
      titleLead: "Find your",
      titleAccent: "next step.",
      sub: ["Overseas travel, moving, birth preparation.", "The bigger the moment,", "the harder it is to shake the feeling that something is missing.", "Volecco helps you find a structured checklist,", "copy it,", "and move forward one step at a time."],
      cta: "Find a checklist",
      demo: "Try the demo",
      proof: [
        { icon: "doc", text: "Sources and last-checked dates" },
        { icon: "download", text: "Run your most recent list offline" },
        { icon: "shield", text: "No empty ratings" },
      ],
    },
    sections: {
      problem: {
        eyebrow: "THE PROBLEM",
        title: ["The feeling that you are forgetting something", "does not go away."],
        lead: ["The moment you enter a new situation,", "the rushed research begins.", "Blogs, videos, forums,", "family group chats.", "The more you read, the more information piles up,", "and the whole picture moves farther away.", "The deadline keeps getting closer."],
        pivot: ["What is missing is not more information.", "It is one checklist that lets you say: this covers it."],
        sources: [
          { id: "s1", label: "Blog post", icon: "doc", hue: 25, cls: "s1" },
          { id: "s2", label: "Explainer video", icon: "play", hue: 350, cls: "s2" },
          { id: "s3", label: "Forum thread", icon: "chat", hue: 280, cls: "s3" },
          { id: "s4", label: "Social post", icon: "globe", hue: 205, cls: "s4" },
          { id: "s5", label: "PDF guide", icon: "note", hue: 150, cls: "s5" },
          { id: "s6", label: "Group chat", icon: "users", hue: 60, cls: "s6" },
        ],
        chaosTitle: "Where do I start?",
        chaosQuestion: "Overseas trip in 3 weeks",
      },
      solution: {
        eyebrow: "THE SOLUTION",
        title: ["Turn scattered wisdom", "into one checklist."],
        lead: ["Volecco organizes experience and public information", "into checklists you can follow from top to bottom.", "Find one,", "copy it to make it yours,", "then move through it one step at a time."],
        tidyTitle: "Overseas trip — Pre-departure list",
        tidySections: [
          { title: "3 weeks before", items: ["Check passport validity", "Check visa or eTA requirements", "Buy travel insurance"] },
          { title: "The night before", items: ["Check suitcase weight", "Check doors and windows at home"] },
        ],
        lastChecked: "Last checked 2026-05",
      },
      how: {
        eyebrow: "HOW IT WORKS",
        title: ["From finding a list", "to finishing it."],
        lead: ["No heavy setup.", "No empty page.", "Five steps turn “Where do I start?”", "into “Next, do this.”"],
        steps: [
          { n: 1, icon: "search", en: "DISCOVER", title: "Find", txt: "Search by situation or keyword and find a checklist that fits your moment." },
          { n: 2, icon: "note", en: "PREVIEW", title: "Check", txt: "Preview every section before copying, so you can choose with confidence." },
          { n: 3, icon: "copy", en: "COPY", title: "Make it yours", txt: "Copy it to My Library. From there, it is your independent data." },
          { n: 4, icon: "edit", en: "PERSONALIZE", title: "Tailor", txt: "Add, remove, and reorder checklist items to fit your situation." },
          { n: 5, icon: "check", en: "EXECUTE", title: "Move forward", txt: "Next Action shows the next step. The board shows your progress." },
        ],
      },
      demo: {
        eyebrow: "THE EXPERIENCE",
        title: ["Only the next step", "stays in focus."],
        lead: ["Copied checklists open in Execute mode.", "You only need to look at one Next Action.", "JourneyTrack shows progress like a route map.", "The demo below is interactive."],
        points: [
          { icon: "flag", title: "Next Action", txt: "The first unfinished checklist item is always shown as one clear card, removing the guesswork." },
          { icon: "plane", title: "JourneyTrack", txt: "Sections become stops on a route, so you can see where you are and how far remains." },
          { icon: "spark2", title: "Focus Mode", txt: "Navigation fades away, leaving a quiet screen for the list in front of you." },
          { icon: "download", title: "Offline execution", txt: "The most recently opened personal list is saved on the device, works offline, and syncs when you return." },
        ],
      },
      categories: {
        eyebrow: "CATEGORIES",
        title: ["Starting with", "three turning points."],
        lead: ["Not hundreds of templates on day one.", "We start where checklist quality matters most.", "Each list is reviewed by an administrator,", "and lists that affect decisions include sources and last-checked dates."],
        note: "Categories will grow from here, little by little.",
        preview: "Preview",
        lastChecked: "Last checked 2026-05",
        cards: [
          { coverLabel: "Sample: pre-departure checklist", hue: 250, catIcon: "plane", cat: "Overseas travel", title: "Preparing for an overseas trip", blurb: "From passports to carry-on bags, move through the weeks before departure in a clear order.", meta: "24 items · 4 sections" },
          { coverLabel: "Sample: moving checklist", hue: 195, catIcon: "home", cat: "Moving / first apartment", title: "Moving and setting up a new home", blurb: "From notice to utilities to the first night of boxes, follow the order and land smoothly.", meta: "28 items · 5 sections" },
          { coverLabel: "Sample: birth preparation checklist", hue: 25, catIcon: "sparkles", cat: "Birth preparation", title: "Preparing before and after birth", blurb: "From the hospital bag to postpartum paperwork, organized in a pace that protects your energy.", meta: "26 items · 5 sections" },
        ],
      },
      trust: {
        eyebrow: "TRUST",
        title: ["Designed to feel", "safe to rely on."],
        lead: ["Checklists can shape real decisions.", "So Volecco puts verifiable context ahead of noisy numbers."],
        note: ["Each list is a preparation aid.", "Sources and last-checked dates are shown,", "and sensitive lists prompt users to confirm the latest official information."],
        cards: [
          { kicker: "SOURCED", title: "Sources and last-checked dates", txt: "For lists involving disaster readiness, health, or public procedures, we show references and review dates. Checking the latest official information can be part of the checklist itself." },
          { kicker: "NO FAKE STARS", title: "No empty ratings", txt: "We do not show hollow stars or reviews. We use factual signals such as Curated, Reviewed, and Copied." },
          { kicker: "OFFLINE FIRST", title: "Works without a signal", txt: "The most recently opened personal list is saved on the device, so it works on a plane or in a new home without internet, then syncs when you return." },
          { kicker: "YOUR COPY", title: "The copied list is yours", txt: "Once copied, it is independent personal data. Updates to the original list will not silently rewrite your copy." },
        ],
      },
      philosophy: {
        eyebrow: "PHILOSOPHY",
        statementLead: "Turn experience",
        statementAccent: "into action",
        statementTail: ".",
        sub: ["A checklist is not just a Todo list.", "It is reusable knowledge.", "The order someone learned the hard way", "can reduce the anxiety of the next person.", "Volecco is a quiet library for that."],
        pills: ["Not a task manager", "Not a wiki", "Not a social network", "A library of reusable knowledge"],
      },
      finalCta: {
        eyebrow: "READY WHEN YOU ARE",
        title: ["Spend less time wondering", "and more time moving."],
        sub: ["Pick a situation,", "copy a checklist,", "and complete the first checklist item.", "You no longer have to hunt for what comes next."],
        cta: "Find a checklist",
        how: "See how it works",
      },
      footer: {
        tag1: ["A checklist navigator for life's turning points.", "So the next thing to do is always visible."],
        tag2: ["Currently preparing as an administrator-curated beta.", "We are starting with a Web app experience that also works well in mobile browsers."],
        product: "Product",
        links: [
          ["how", "How it works"],
          ["demo", "Demo"],
          ["categories", "Categories"],
          ["trust", "Trust"],
        ],
        copy: "© 2026 Volecco — Curated checklists (beta)",
      },
    },
    mockups: {
      situations: [
        { flap: "OVERSEAS TRIP", status: "NOW BOARDING", tone: "next", step: "Check passport validity", label: "Overseas trip" },
        { flap: "MOVING HOUSE", status: "ON TIME", tone: "live", step: "Give notice for your current place", label: "Moving house" },
        { flap: "NEW BABY", status: "STAND BY", tone: "todo", step: "Install the child seat", label: "New baby" },
        { flap: "NEW APARTMENT", status: "ON TIME", tone: "live", step: "Set up electricity, gas, and water", label: "First apartment" },
        { flap: "BIRTH PREP", status: "NOW BOARDING", tone: "next", step: "Pack the hospital bag", label: "Birth preparation" },
        { flap: "VISA & DOCS", status: "STAND BY", tone: "todo", step: "Check visa requirements", label: "Visa and documents" },
      ],
      bigBoard: { live: "VOLECCO · DEPARTURES", cols: ["SITUATION", "STATUS", "NEXT STEP"], aria: "Next Action" },
      execute: {
        tryMe: "TRY ME",
        title: "Overseas trip — Pre-departure checklist",
        category: "Overseas travel",
        doneUnit: "done",
        pctDone: "done",
        nextAction: "NEXT ACTION",
        markDone: "Mark this checklist item done",
        celebrate: "Everything is done. Nice work.",
        reset: "Reset",
        catName: "Travel",
        sections: [
          { title: "3 weeks before", items: [{ text: "Check passport validity", done: true }, { text: "Check visa or eTA requirements", done: true }, { text: "Buy travel insurance", done: true }] },
          { title: "1 week before", items: [{ text: "Download offline maps", done: true }, { text: "Copy your passport and cards", done: false }, { text: "Share emergency contacts with family", done: false }] },
          { title: "Carry-on", items: [{ text: "Charger and power bank", done: false }, { text: "Keep medicine in original packaging", done: false }] },
        ],
      },
      miniBoard: { live: "NOW BOARDING", cols: "Situation · next step", nextStep: "NEXT STEP" },
    },
    common: { curated: "CURATED" },
  };

  window.SolariLandingCopy = { ja, en };
})();
